[package]
name = "murkdown"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[lib]
name = "murkdown"
path = "src/lib/lib.rs"
doctest = false

[[bin]]
name = "md"
path = "src/main.rs"

[dependencies]
